Modules Release 4.8.0 (2021-07-14)
DCC-SW: Added modules (2023-aug/XeonE5-2660v3)
DCC-SW: Removed standard modules: /apps/dcc/etc/ModulesSL73/modulefiles
DCC-SW: Using gnu/12.3.0 compiler (requested)
DCC-SW: Released modules (2023-aug/XeonE5-2660v3)
DCC-SW: Added modules (2020-aug/XeonE5-2660v3)
DCC-SW: Removed standard modules: /apps/dcc/etc/ModulesSL73/modulefiles
DCC-SW: Using gnu/9.3.0 compiler
Loading python/3.8.5
  Loading requirement: build-tools/1.0 gcc/9.3.0 zlib/1.2.11 expat/2.2.0
    libffi/3.3
Loading scalapack/2.1.0
  Loading requirement: numactl/2.0.12 libxml2/2.9.10 hwloc/2.2.0 knem/1.1.4
    ucx/1.8.1 openmpi/4.0.4
rank=01 L00: Traceback (most recent call last):
rank=01 L01:   File "plot_6.py", line 46, in <module>
rank=01 L02:     energy = atoms.get_potential_energy()
rank=01 L03:   File "/zhome/87/8/147075/venv-name/ase/ase/atoms.py", line 755, in get_potential_energy
rank=01 L04:     energy = self._calc.get_potential_energy(self)
rank=01 L05:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 253, in get_potential_energy
rank=01 L06:     return self.calculate_property(atoms,
rank=01 L07:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 167, in calculate_property
rank=01 L08:     self.converge()
rank=01 L09:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 226, in converge
rank=01 L10:     self.calculation.converge(calculate_forces=self._calculate_forces)
rank=01 L11:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 171, in converge
rank=01 L12:     for step, _ in enumerate(self.iconverge(convergence,
rank=01 L13:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 158, in iconverge
rank=01 L14:     yield from self.scf_loop.iterate(self.state,
rank=01 L15:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/scf.py", line 103, in iterate
rank=01 L16:     raise KohnShamConvergenceError
rank=01 L17: gpaw.KohnShamConvergenceError
rank=02 L00: Traceback (most recent call last):
rank=02 L01:   File "plot_6.py", line 46, in <module>
rank=02 L02:     energy = atoms.get_potential_energy()
rank=02 L03:   File "/zhome/87/8/147075/venv-name/ase/ase/atoms.py", line 755, in get_potential_energy
rank=02 L04:     energy = self._calc.get_potential_energy(self)
rank=02 L05:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 253, in get_potential_energy
rank=02 L06:     return self.calculate_property(atoms,
rank=02 L07:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 167, in calculate_property
rank=02 L08:     self.converge()
rank=02 L09:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 226, in converge
rank=02 L10:     self.calculation.converge(calculate_forces=self._calculate_forces)
rank=02 L11:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 171, in converge
rank=02 L12:     for step, _ in enumerate(self.iconverge(convergence,
rank=02 L13:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 158, in iconverge
rank=02 L14:     yield from self.scf_loop.iterate(self.state,
rank=02 L15:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/scf.py", line 103, in iterate
rank=02 L16:     raise KohnShamConvergenceError
rank=02 L17: gpaw.KohnShamConvergenceError
GPAW CLEANUP (node 2): <class 'gpaw.KohnShamConvergenceError'> occurred.  Calling MPI_Abort!
rank=03 L00: Traceback (most recent call last):
rank=03 L01:   File "plot_6.py", line 46, in <module>
rank=03 L02:     energy = atoms.get_potential_energy()
rank=03 L03:   File "/zhome/87/8/147075/venv-name/ase/ase/atoms.py", line 755, in get_potential_energy
rank=03 L04:     energy = self._calc.get_potential_energy(self)
rank=03 L05:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 253, in get_potential_energy
rank=03 L06:     return self.calculate_property(atoms,
rank=03 L07:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 167, in calculate_property
rank=03 L08:     self.converge()
rank=03 L09:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 226, in converge
rank=03 L10:     self.calculation.converge(calculate_forces=self._calculate_forces)
rank=03 L11:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 171, in converge
rank=03 L12:     for step, _ in enumerate(self.iconverge(convergence,
rank=03 L13:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 158, in iconverge
rank=03 L14:     yield from self.scf_loop.iterate(self.state,
rank=03 L15:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/scf.py", line 103, in iterate
rank=03 L16:     raise KohnShamConvergenceError
rank=03 L17: gpaw.KohnShamConvergenceError
GPAW CLEANUP (node 3): <class 'gpaw.KohnShamConvergenceError'> occurred.  Calling MPI_Abort!
rank=04 L00: Traceback (most recent call last):
rank=04 L01:   File "plot_6.py", line 46, in <module>
rank=04 L02:     energy = atoms.get_potential_energy()
rank=04 L03:   File "/zhome/87/8/147075/venv-name/ase/ase/atoms.py", line 755, in get_potential_energy
rank=04 L04:     energy = self._calc.get_potential_energy(self)
rank=04 L05:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 253, in get_potential_energy
rank=04 L06:     return self.calculate_property(atoms,
rank=04 L07:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 167, in calculate_property
rank=04 L08:     self.converge()
rank=04 L09:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 226, in converge
rank=04 L10:     self.calculation.converge(calculate_forces=self._calculate_forces)
rank=04 L11:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 171, in converge
rank=04 L12:     for step, _ in enumerate(self.iconverge(convergence,
rank=04 L13:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 158, in iconverge
rank=04 L14:     yield from self.scf_loop.iterate(self.state,
rank=04 L15:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/scf.py", line 103, in iterate
rank=04 L16:     raise KohnShamConvergenceError
rank=04 L17: gpaw.KohnShamConvergenceError
GPAW CLEANUP (node 4): <class 'gpaw.KohnShamConvergenceError'> occurred.  Calling MPI_Abort!
rank=06 L00: Traceback (most recent call last):
rank=06 L01:   File "plot_6.py", line 46, in <module>
rank=06 L02:     energy = atoms.get_potential_energy()
rank=06 L03:   File "/zhome/87/8/147075/venv-name/ase/ase/atoms.py", line 755, in get_potential_energy
rank=06 L04:     energy = self._calc.get_potential_energy(self)
rank=06 L05:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 253, in get_potential_energy
rank=06 L06:     return self.calculate_property(atoms,
rank=06 L07:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 167, in calculate_property
rank=06 L08:     self.converge()
rank=06 L09:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 226, in converge
rank=06 L10:     self.calculation.converge(calculate_forces=self._calculate_forces)
rank=06 L11:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 171, in converge
rank=06 L12:     for step, _ in enumerate(self.iconverge(convergence,
rank=06 L13:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 158, in iconverge
rank=06 L14:     yield from self.scf_loop.iterate(self.state,
rank=06 L15:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/scf.py", line 103, in iterate
rank=06 L16:     raise KohnShamConvergenceError
rank=06 L17: gpaw.KohnShamConvergenceError
GPAW CLEANUP (node 6): <class 'gpaw.KohnShamConvergenceError'> occurred.  Calling MPI_Abort!
rank=08 L00: Traceback (most recent call last):
rank=08 L01:   File "plot_6.py", line 46, in <module>
rank=08 L02:     energy = atoms.get_potential_energy()
rank=08 L03:   File "/zhome/87/8/147075/venv-name/ase/ase/atoms.py", line 755, in get_potential_energy
rank=08 L04:     energy = self._calc.get_potential_energy(self)
rank=08 L05:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 253, in get_potential_energy
rank=08 L06:     return self.calculate_property(atoms,
rank=08 L07:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 167, in calculate_property
rank=08 L08:     self.converge()
rank=08 L09:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 226, in converge
rank=08 L10:     self.calculation.converge(calculate_forces=self._calculate_forces)
rank=08 L11:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 171, in converge
rank=08 L12:     for step, _ in enumerate(self.iconverge(convergence,
rank=08 L13:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 158, in iconverge
rank=08 L14:     yield from self.scf_loop.iterate(self.state,
rank=08 L15:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/scf.py", line 103, in iterate
rank=08 L16:     raise KohnShamConvergenceError
rank=08 L17: gpaw.KohnShamConvergenceError
GPAW CLEANUP (node 8): <class 'gpaw.KohnShamConvergenceError'> occurred.  Calling MPI_Abort!
rank=09 L00: Traceback (most recent call last):
rank=09 L01:   File "plot_6.py", line 46, in <module>
rank=09 L02:     energy = atoms.get_potential_energy()
rank=09 L03:   File "/zhome/87/8/147075/venv-name/ase/ase/atoms.py", line 755, in get_potential_energy
rank=09 L04:     energy = self._calc.get_potential_energy(self)
rank=09 L05:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 253, in get_potential_energy
rank=09 L06:     return self.calculate_property(atoms,
rank=09 L07:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 167, in calculate_property
rank=09 L08:     self.converge()
rank=09 L09:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 226, in converge
rank=09 L10:     self.calculation.converge(calculate_forces=self._calculate_forces)
rank=09 L11:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 171, in converge
rank=09 L12:     for step, _ in enumerate(self.iconverge(convergence,
rank=09 L13:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 158, in iconverge
rank=09 L14:     yield from self.scf_loop.iterate(self.state,
rank=09 L15:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/scf.py", line 103, in iterate
rank=09 L16:     raise KohnShamConvergenceError
rank=09 L17: gpaw.KohnShamConvergenceError
GPAW CLEANUP (node 9): <class 'gpaw.KohnShamConvergenceError'> occurred.  Calling MPI_Abort!
rank=05 L00: Traceback (most recent call last):
rank=05 L01:   File "plot_6.py", line 46, in <module>
rank=05 L02:     energy = atoms.get_potential_energy()
rank=05 L03:   File "/zhome/87/8/147075/venv-name/ase/ase/atoms.py", line 755, in get_potential_energy
rank=05 L04:     energy = self._calc.get_potential_energy(self)
rank=05 L05:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 253, in get_potential_energy
rank=05 L06:     return self.calculate_property(atoms,
rank=05 L07:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 167, in calculate_property
rank=05 L08:     self.converge()
rank=05 L09:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 226, in converge
rank=05 L10:     self.calculation.converge(calculate_forces=self._calculate_forces)
rank=05 L11:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 171, in converge
rank=05 L12:     for step, _ in enumerate(self.iconverge(convergence,
rank=05 L13:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 158, in iconverge
rank=05 L14:     yield from self.scf_loop.iterate(self.state,
rank=05 L15:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/scf.py", line 103, in iterate
rank=05 L16:     raise KohnShamConvergenceError
rank=05 L17: gpaw.KohnShamConvergenceError
rank=07 L00: Traceback (most recent call last):
rank=07 L01:   File "plot_6.py", line 46, in <module>
rank=07 L02:     energy = atoms.get_potential_energy()
rank=07 L03:   File "/zhome/87/8/147075/venv-name/ase/ase/atoms.py", line 755, in get_potential_energy
rank=07 L04:     energy = self._calc.get_potential_energy(self)
rank=07 L05:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 253, in get_potential_energy
rank=07 L06:     return self.calculate_property(atoms,
rank=07 L07:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 167, in calculate_property
rank=07 L08:     self.converge()
rank=07 L09:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 226, in converge
rank=07 L10:     self.calculation.converge(calculate_forces=self._calculate_forces)
rank=07 L11:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 171, in converge
rank=07 L12:     for step, _ in enumerate(self.iconverge(convergence,
rank=07 L13:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 158, in iconverge
rank=07 L14:     yield from self.scf_loop.iterate(self.state,
rank=07 L15:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/scf.py", line 103, in iterate
rank=07 L16:     raise KohnShamConvergenceError
rank=07 L17: gpaw.KohnShamConvergenceError
GPAW CLEANUP (node 7): <class 'gpaw.KohnShamConvergenceError'> occurred.  Calling MPI_Abort!
rank=11 L00: Traceback (most recent call last):
rank=11 L01:   File "plot_6.py", line 46, in <module>
rank=11 L02:     energy = atoms.get_potential_energy()
rank=11 L03:   File "/zhome/87/8/147075/venv-name/ase/ase/atoms.py", line 755, in get_potential_energy
rank=11 L04:     energy = self._calc.get_potential_energy(self)
rank=11 L05:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 253, in get_potential_energy
rank=11 L06:     return self.calculate_property(atoms,
rank=11 L07:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 167, in calculate_property
rank=11 L08:     self.converge()
rank=11 L09:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 226, in converge
rank=11 L10:     self.calculation.converge(calculate_forces=self._calculate_forces)
rank=11 L11:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 171, in converge
rank=11 L12:     for step, _ in enumerate(self.iconverge(convergence,
rank=11 L13:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 158, in iconverge
rank=11 L14:     yield from self.scf_loop.iterate(self.state,
rank=11 L15:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/scf.py", line 103, in iterate
rank=11 L16:     raise KohnShamConvergenceError
rank=11 L17: gpaw.KohnShamConvergenceError
GPAW CLEANUP (node 11): <class 'gpaw.KohnShamConvergenceError'> occurred.  Calling MPI_Abort!
rank=00 L00: Traceback (most recent call last):
rank=00 L01:   File "plot_6.py", line 46, in <module>
rank=00 L02:     energy = atoms.get_potential_energy()
rank=00 L03:   File "/zhome/87/8/147075/venv-name/ase/ase/atoms.py", line 755, in get_potential_energy
rank=00 L04:     energy = self._calc.get_potential_energy(self)
rank=00 L05:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 253, in get_potential_energy
rank=00 L06:     return self.calculate_property(atoms,
rank=00 L07:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 167, in calculate_property
rank=00 L08:     self.converge()
rank=00 L09:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 226, in converge
rank=00 L10:     self.calculation.converge(calculate_forces=self._calculate_forces)
rank=00 L11:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 171, in converge
rank=00 L12:     for step, _ in enumerate(self.iconverge(convergence,
rank=00 L13:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 158, in iconverge
rank=00 L14:     yield from self.scf_loop.iterate(self.state,
rank=00 L15:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/scf.py", line 103, in iterate
rank=00 L16:     raise KohnShamConvergenceError
rank=00 L17: gpaw.KohnShamConvergenceError
GPAW CLEANUP (node 0): <class 'gpaw.KohnShamConvergenceError'> occurred.  Calling MPI_Abort!
GPAW CLEANUP (node 1): <class 'gpaw.KohnShamConvergenceError'> occurred.  Calling MPI_Abort!
GPAW CLEANUP (node 5): <class 'gpaw.KohnShamConvergenceError'> occurred.  Calling MPI_Abort!
rank=10 L00: Traceback (most recent call last):
rank=10 L01:   File "plot_6.py", line 46, in <module>
rank=10 L02:     energy = atoms.get_potential_energy()
rank=10 L03:   File "/zhome/87/8/147075/venv-name/ase/ase/atoms.py", line 755, in get_potential_energy
rank=10 L04:     energy = self._calc.get_potential_energy(self)
rank=10 L05:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 253, in get_potential_energy
rank=10 L06:     return self.calculate_property(atoms,
rank=10 L07:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 167, in calculate_property
rank=10 L08:     self.converge()
rank=10 L09:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/ase_interface.py", line 226, in converge
rank=10 L10:     self.calculation.converge(calculate_forces=self._calculate_forces)
rank=10 L11:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 171, in converge
rank=10 L12:     for step, _ in enumerate(self.iconverge(convergence,
rank=10 L13:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/calculation.py", line 158, in iconverge
rank=10 L14:     yield from self.scf_loop.iterate(self.state,
rank=10 L15:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/new/scf.py", line 103, in iterate
rank=10 L16:     raise KohnShamConvergenceError
rank=10 L17: gpaw.KohnShamConvergenceError
GPAW CLEANUP (node 10): <class 'gpaw.KohnShamConvergenceError'> occurred.  Calling MPI_Abort!
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 7 in communicator MPI_COMM_WORLD
with errorcode 42.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[n-62-28-34:32150] PMIX ERROR: UNREACHABLE in file ../../../../../../../opal/mca/pmix/pmix3x/pmix/src/server/pmix_server.c at line 2193
[n-62-28-34:32150] 11 more processes have sent help message help-mpi-api.txt / mpi-abort
[n-62-28-34:32150] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
