Modules Release 4.8.0 (2021-07-14)
DCC-SW: Added modules (2023-aug/XeonE5-2660v3)
DCC-SW: Removed standard modules: /apps/dcc/etc/ModulesSL73/modulefiles
DCC-SW: Using gnu/12.3.0 compiler (requested)
DCC-SW: Released modules (2023-aug/XeonE5-2660v3)
DCC-SW: Added modules (2020-aug/XeonE5-2660v3)
DCC-SW: Removed standard modules: /apps/dcc/etc/ModulesSL73/modulefiles
DCC-SW: Using gnu/9.3.0 compiler
Loading python/3.8.5
  Loading requirement: build-tools/1.0 gcc/9.3.0 zlib/1.2.11 expat/2.2.0
    libffi/3.3
Loading scalapack/2.1.0
  Loading requirement: numactl/2.0.12 libxml2/2.9.10 hwloc/2.2.0 knem/1.1.4
    ucx/1.8.1 openmpi/4.0.4
rank=10 L0: Traceback (most recent call last):
rank=10 L1:   File "soc.py", line 63, in <module>
rank=10 L2:     en_soc = soc_eigenstates(calc=calc, projected=True, theta=theta, phi=phi,
rank=10 L3:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 520, in soc_eigenstates
rank=10 L4:     bzwfs = soc_eigenstates_raw(ibzwfs,
rank=10 L5:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 370, in soc_eigenstates_raw
rank=10 L6:     for ibz_index, ibzwf in ibzwfs:
rank=10 L7:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 442, in extract_ibz_wave_functions
rank=10 L8:     projections.matrix.array[:] = P1_nI[n1:n2]
rank=10 L9: ValueError: could not broadcast input array from shape (106,132) into shape (106,264)
GPAW CLEANUP (node 10): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=04 L0: Traceback (most recent call last):
rank=04 L1:   File "soc.py", line 63, in <module>
rank=04 L2:     en_soc = soc_eigenstates(calc=calc, projected=True, theta=theta, phi=phi,
rank=04 L3:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 520, in soc_eigenstates
rank=04 L4:     bzwfs = soc_eigenstates_raw(ibzwfs,
rank=04 L5:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 370, in soc_eigenstates_raw
rank=04 L6:     for ibz_index, ibzwf in ibzwfs:
rank=04 L7:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 442, in extract_ibz_wave_functions
rank=04 L8:     projections.matrix.array[:] = P1_nI[n1:n2]
rank=04 L9: ValueError: could not broadcast input array from shape (106,132) into shape (106,264)
GPAW CLEANUP (node 4): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=08 L0: Traceback (most recent call last):
rank=08 L1:   File "soc.py", line 63, in <module>
rank=08 L2:     en_soc = soc_eigenstates(calc=calc, projected=True, theta=theta, phi=phi,
rank=08 L3:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 520, in soc_eigenstates
rank=08 L4:     bzwfs = soc_eigenstates_raw(ibzwfs,
rank=08 L5:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 370, in soc_eigenstates_raw
rank=08 L6:     for ibz_index, ibzwf in ibzwfs:
rank=08 L7:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 442, in extract_ibz_wave_functions
rank=08 L8:     projections.matrix.array[:] = P1_nI[n1:n2]
rank=08 L9: ValueError: could not broadcast input array from shape (106,132) into shape (106,264)
GPAW CLEANUP (node 8): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=00 L0: Traceback (most recent call last):
rank=00 L1:   File "soc.py", line 63, in <module>
rank=00 L2:     en_soc = soc_eigenstates(calc=calc, projected=True, theta=theta, phi=phi,
rank=00 L3:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 520, in soc_eigenstates
rank=00 L4:     bzwfs = soc_eigenstates_raw(ibzwfs,
rank=00 L5:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 370, in soc_eigenstates_raw
rank=00 L6:     for ibz_index, ibzwf in ibzwfs:
rank=00 L7:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 442, in extract_ibz_wave_functions
rank=00 L8:     projections.matrix.array[:] = P1_nI[n1:n2]
rank=00 L9: ValueError: could not broadcast input array from shape (106,132) into shape (106,264)
GPAW CLEANUP (node 0): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=02 L0: Traceback (most recent call last):
rank=02 L1:   File "soc.py", line 63, in <module>
rank=02 L2:     en_soc = soc_eigenstates(calc=calc, projected=True, theta=theta, phi=phi,
rank=02 L3:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 520, in soc_eigenstates
rank=02 L4:     bzwfs = soc_eigenstates_raw(ibzwfs,
rank=02 L5:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 370, in soc_eigenstates_raw
rank=02 L6:     for ibz_index, ibzwf in ibzwfs:
rank=02 L7:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 442, in extract_ibz_wave_functions
rank=02 L8:     projections.matrix.array[:] = P1_nI[n1:n2]
rank=02 L9: ValueError: could not broadcast input array from shape (106,132) into shape (106,264)
GPAW CLEANUP (node 2): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=06 L0: Traceback (most recent call last):
rank=06 L1:   File "soc.py", line 63, in <module>
rank=06 L2:     en_soc = soc_eigenstates(calc=calc, projected=True, theta=theta, phi=phi,
rank=06 L3:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 520, in soc_eigenstates
rank=06 L4:     bzwfs = soc_eigenstates_raw(ibzwfs,
rank=06 L5:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 370, in soc_eigenstates_raw
rank=06 L6:     for ibz_index, ibzwf in ibzwfs:
rank=06 L7:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 442, in extract_ibz_wave_functions
rank=06 L8:     projections.matrix.array[:] = P1_nI[n1:n2]
rank=06 L9: ValueError: could not broadcast input array from shape (106,132) into shape (106,264)
GPAW CLEANUP (node 6): <class 'ValueError'> occurred.  Calling MPI_Abort!
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 10 in communicator MPI_COMM_WORLD
with errorcode 42.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[n-62-28-22:18427] PMIX ERROR: UNREACHABLE in file ../../../../../../../opal/mca/pmix/pmix3x/pmix/src/server/pmix_server.c at line 2193
[n-62-28-22:18427] PMIX ERROR: UNREACHABLE in file ../../../../../../../opal/mca/pmix/pmix3x/pmix/src/server/pmix_server.c at line 2193
[n-62-28-22:18427] PMIX ERROR: UNREACHABLE in file ../../../../../../../opal/mca/pmix/pmix3x/pmix/src/server/pmix_server.c at line 2193
[n-62-28-22:18427] PMIX ERROR: UNREACHABLE in file ../../../../../../../opal/mca/pmix/pmix3x/pmix/src/server/pmix_server.c at line 2193
[n-62-28-22:18427] PMIX ERROR: UNREACHABLE in file ../../../../../../../opal/mca/pmix/pmix3x/pmix/src/server/pmix_server.c at line 2193
[n-62-28-22:18427] 5 more processes have sent help message help-mpi-api.txt / mpi-abort
[n-62-28-22:18427] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
